// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: keazlxzacmnssrjvfsyq

class SupabaseConfig {
  static const String supabaseUrl = 'https://keazlxzacmnssrjvfsyq.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlYXpseHphY21uc3NyanZmc3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxNDE0NTYsImV4cCI6MjA3ODcxNzQ1Nn0.90_Ov3mvg7p9BX9MDb7hObG69gebyKihbR0P_d5_eF0';
}
